version: '3.4'

services:
 catalogdb:
   container_name: eshop.catalogdb
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=CatalogDb
   restart: always
   ports:
    - "5432:5432"
   volumes:
    - eshop_postgres_catalog:/var/lib/postgresql/data/ 